### PR TITLE
Controller class that handles the "add entry" operation of the addres…

### PR DESCRIPTION
**Pull request by Overrideveloper**
…s book. It isn't yet complete though.

### CODE REVIEW

**Comment by Ken-Maximus** [comment]
@Overrideveloper  Completed the UI of the Add Entry operation and also added ActionListeners to the buttons.

**Comment by nish06** [comment]
@Overrideveloper  @Ken-Maximus  Why don't we setResizable to false?, since the UI is rather small.

**Comment by Overrideveloper** [comment]
@nish06 Now that you mention it, I think that would be better. @Ken-Maximus Don't you think so?

**Comment by Ken-Maximus** [comment]
@Overrideveloper  I think so too. @nish06  Nice one.

**Comment by nish06** [comment]
I think we are done with this part of the address book. Don't you think so? @Overrideveloper @Ken-Maximus

**Comment by Overrideveloper** [comment]
@nish06 I think we are. @Ken-Maximus?

**Comment by Ken-Maximus** [comment]
I believe we are. @Overrideveloper @nish06

**Pull request merged**
